import { Poppins } from 'next/font/google'
import './globals.css'
import RegisterModal from './components/modals/RegisterModal';
import LoginModal from './components/modals/LoginModal';

const poppins = Poppins({
  weight: ["400", "900"],   
  display: "swap",
  subsets: ["latin"],
  variable: "--poppins-font",
});

export const metadata = {
  title: 'Trible',
  description: 'Generated by Trible',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}
        <RegisterModal />
        <LoginModal />
      </body>

    </html>
  )
}
